# Generated by Django 6.1.1 on 2026-09-04 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='score',
            field=models.IntegerField(default=0, help_text='Points awarded for a correct answer'),
        ),
    ]
